"""initial schema

Revision ID: 8248e2193db2
Revises: 
Create Date: 2026-08-27 21:48:22.057154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.storage.tables


revision: str = '8248e2193db2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('entry_time', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('exit_time', app.storage.tables.UTCDateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bt_trades', 'backtest_trades', ['backtest_id'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('start', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtests_strategy', 'backtests', ['strategy', 'created_at'], unique=False)
    op.create_table('decision_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=12), nullable=False),
    sa.Column('failed_stage', sa.String(length=30), nullable=True),
    sa.Column('venue', sa.String(length=12), nullable=True),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_time', 'decision_records', ['timestamp'], unique=False)
    op.create_table('external_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assets', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('body_excerpt', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('confirmation_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('decay_half_life_hours', sa.Float(), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('cluster_key', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash', name='uq_external_event_hash')
    )
    op.create_index('ix_ext_events_cluster', 'external_events', ['cluster_key'], unique=False)
    op.create_index('ix_ext_events_time', 'external_events', ['timestamp'], unique=False)
    op.create_table('features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_feature')
    )
    op.create_index('ix_features_lookup', 'features', ['symbol', 'timeframe', 'timestamp'], unique=False)
    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('open_time', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('close_time', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('taker_buy_base', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'open_time', name='uq_candle')
    )
    op.create_index('ix_candles_lookup', 'market_candles', ['symbol', 'timeframe', 'open_time'], unique=False)
    op.create_table('market_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('timestamp_event', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('timestamp_received', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_hash', name='uq_market_event_hash')
    )
    op.create_index('ix_market_events_symbol', 'market_events', ['symbol', 'kind', 'timestamp_event'], unique=False)
    op.create_index('ix_market_events_time', 'market_events', ['timestamp_event'], unique=False)
    op.create_table('orderbook_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('bids', sa.JSON(), nullable=False),
    sa.Column('asks', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ob_symbol_time', 'orderbook_snapshots', ['symbol', 'timestamp'], unique=False)
    op.create_table('paper_fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('qty', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('fee', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('fee_asset', sa.String(length=10), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_maker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_fills_order', 'paper_fills', ['order_id'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('client_order_id', sa.String(length=40), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=40), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('time_in_force', sa.String(length=3), nullable=False),
    sa.Column('quantity', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_qty', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('avg_fill_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('created_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_paper_orders_coid')
    )
    op.create_index('ix_paper_orders_symbol', 'paper_orders', ['symbol', 'status'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('qty', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('avg_entry_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('stop_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('target_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('opened_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', app.storage.tables.UTCDateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('fees_paid', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('close_reason', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_positions_open', 'paper_positions', ['symbol', 'closed_at'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=12), nullable=False),
    sa.Column('equity', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('cash', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('unrealized_pnl', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('realized_pnl_today', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('drawdown_pct', sa.Float(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_perf_snap', 'performance_snapshots', ['venue', 'timestamp'], unique=False)
    op.create_table('regime_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(length=20), nullable=False),
    sa.Column('volatility_state', sa.String(length=20), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_regime_hist', 'regime_history', ['symbol', 'timestamp'], unique=False)
    op.create_table('risk_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_events_time', 'risk_events', ['timestamp'], unique=False)
    op.create_table('signal_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('supports', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_signal', 'signal_evidence', ['signal_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_edge_bps', sa.Float(), nullable=False),
    sa.Column('invalidation_level', sa.Float(), nullable=True),
    sa.Column('hypothetical_stop', sa.Float(), nullable=True),
    sa.Column('hypothetical_target', sa.Float(), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=False),
    sa.Column('data_quality', sa.Float(), nullable=False),
    sa.Column('external_confirmation', sa.Float(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_symbol_time', 'signals', ['symbol', 'timestamp'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('healthy', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=500), nullable=False),
    sa.Column('events_seen', sa.Integer(), nullable=False),
    sa.Column('lag_seconds', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_health', 'source_health', ['source', 'timestamp'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('strategies',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('stage', sa.String(length=15), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.String(length=20), nullable=False),
    sa.Column('scorecard', sa.Float(), nullable=False),
    sa.Column('updated_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('created_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy', 'version', name='uq_strategy_version')
    )
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_events_time', 'system_events', ['timestamp'], unique=False)
    op.create_table('testnet_fills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('qty', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('fee', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('fee_asset', sa.String(length=10), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('is_maker', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_testnet_fills_order', 'testnet_fills', ['order_id'], unique=False)
    op.create_table('testnet_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('intent_id', sa.String(length=36), nullable=False),
    sa.Column('client_order_id', sa.String(length=40), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=40), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('time_in_force', sa.String(length=3), nullable=False),
    sa.Column('quantity', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled_qty', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('avg_fill_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('created_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id', name='uq_testnet_orders_coid')
    )
    op.create_index('ix_testnet_orders_symbol', 'testnet_orders', ['symbol', 'status'], unique=False)
    op.create_table('testnet_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('qty', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('avg_entry_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('stop_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('target_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('opened_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', app.storage.tables.UTCDateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('fees_paid', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('close_reason', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_testnet_positions_open', 'testnet_positions', ['symbol', 'closed_at'], unique=False)
    op.create_table('trade_intents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('signal_score', sa.Float(), nullable=False),
    sa.Column('reference_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('limit_price', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('quantity', app.storage.tables.MoneyType(precision=38, scale=18), nullable=False),
    sa.Column('hypothetical_stop', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('hypothetical_target', app.storage.tables.MoneyType(precision=38, scale=18), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('invalidation', sa.String(length=500), nullable=False),
    sa.Column('venue', sa.String(length=12), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('created_at', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('is_buyer_maker', sa.Boolean(), nullable=False),
    sa.Column('timestamp', app.storage.tables.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'trade_id', name='uq_trade')
    )
    op.create_index('ix_trades_symbol_time', 'trades', ['symbol', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_symbol_time', table_name='trades')
    op.drop_table('trades')
    op.drop_table('trade_intents')
    op.drop_index('ix_testnet_positions_open', table_name='testnet_positions')
    op.drop_table('testnet_positions')
    op.drop_index('ix_testnet_orders_symbol', table_name='testnet_orders')
    op.drop_table('testnet_orders')
    op.drop_index('ix_testnet_fills_order', table_name='testnet_fills')
    op.drop_table('testnet_fills')
    op.drop_index('ix_system_events_time', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('strategy_versions')
    op.drop_table('strategies')
    op.drop_table('sources')
    op.drop_index('ix_source_health', table_name='source_health')
    op.drop_table('source_health')
    op.drop_index('ix_signals_symbol_time', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_evidence_signal', table_name='signal_evidence')
    op.drop_table('signal_evidence')
    op.drop_index('ix_risk_events_time', table_name='risk_events')
    op.drop_table('risk_events')
    op.drop_index('ix_regime_hist', table_name='regime_history')
    op.drop_table('regime_history')
    op.drop_index('ix_perf_snap', table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index('ix_paper_positions_open', table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index('ix_paper_orders_symbol', table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index('ix_paper_fills_order', table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index('ix_ob_symbol_time', table_name='orderbook_snapshots')
    op.drop_table('orderbook_snapshots')
    op.drop_index('ix_market_events_time', table_name='market_events')
    op.drop_index('ix_market_events_symbol', table_name='market_events')
    op.drop_table('market_events')
    op.drop_index('ix_candles_lookup', table_name='market_candles')
    op.drop_table('market_candles')
    op.drop_index('ix_features_lookup', table_name='features')
    op.drop_table('features')
    op.drop_index('ix_ext_events_time', table_name='external_events')
    op.drop_index('ix_ext_events_cluster', table_name='external_events')
    op.drop_table('external_events')
    op.drop_index('ix_decisions_time', table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index('ix_backtests_strategy', table_name='backtests')
    op.drop_table('backtests')
    op.drop_index('ix_bt_trades', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    # ### end Alembic commands ###
